<?php

$produtos = [
    // Tortas
    [
        'nome' => 'Torta de abóbora',
        'img' => '1564686701281-PUMPKIN-PIE.jpg',
        'destaque' => true,
        'preco' => 15,
        'descricao' => "Esta sobremesa tradicional do Dia de Ação de Graças nos Estados Unidos não é muito comum por aqui. Ou melhor: não era! Pode apostar: vai virar hit na sua casa.",
        'categorias' => [2, 6],
    ],
    [
        'nome' => 'Torta rústica de abóbora',
        'img' => '1503598813494-torta-abobora.jpg',
        'destaque' => true,
        'preco' => 22,
        'descricao' => "Esta receita ganha um toque de inverno com a abóbora paulista. É linda e prática. Boa para aproveitar os legumes, ainda pode ser preparada em etapas: deixe a massa pronta em um dia, monte e asse a torta no outro.",
        'categorias' => [2, 6],
    ],
    [
        'nome' => 'Torta de ricota com pêssegos macerados',
        'img' => '1513772226125-cheesecake.jpg',
        'destaque' => true,
        'preco' => 20,
        'descricao' => "Uma torta de sabor suave, supercremosa, pronta para receber a cobertura que você quiser. Aqui, fomos de pêssegos macerados com vinho. Chique!",
        'categorias' => [2],
    ],
    [
        'nome' => 'Torta de caqui com creme de limão',
        'img' => '1554228928264-IMG_9592.jpg',
        'destaque' => false,
        'preco' => 21,
        'descricao' => "Quem já comeu caqui na torta? Fica uma delícia! Para ficar assim dourado, ele passa pela frigideira com um pouquinho de manteiga. A combinação com o creme de limão equilibra doce e azedo.",
        'categorias' => [2],
    ],
    [
        'nome' => 'Torta de limão com merengue',
        'img' => '1555953378481-CP-2019-31-01_6624_.jpg',
        'destaque' => true,
        'preco' => 20,
        'descricao' => "De básica esta torta não tem nada. O segredo está na gema de ovo: ela deixa o creme brilhante, sedoso e amarelinho. Ponto também para a decoração queimada, um luxo!",
        'categorias' => [2],
    ],
    [
        'nome' => 'Torta de banana',
        'img' => '1597953473440-tortareceita.jpg',
        'destaque' => true,
        'preco' => 20,
        'descricao' => "O açúcar mascavo dá um gostinho especial – mais complexo – a essa torta clássica e com gosto de comida-conforto. Uma pitada de canela faz dupla imbatível com a banana-nanica.",
        'categorias' => [2],
    ],
    [
        'nome' => 'Torta de castanha-de-caju e damasco',
        'img' => '1131588000000-Torta-de-castanha-de-caju-e-damasco.jpg',
        'destaque' => true,
        'preco' => 20,
        'descricao' => "Receitas saudáveis não são associadas à elegância... Não eram! Esta sofisticada torta é integralmente chique e deliciosa.",
        'categorias' => [2],
    ],
    [
        'nome' => 'Torta de chocolate com damasco',
        'img' => '955076400000-Torta-de-chocolate-com-damasco.jpg',
        'destaque' => true,
        'preco' => 20,
        'descricao' => "A combinação fina e delicada dos damascos com o chocolate faz desta sobremesa uma torta muito especial. Ideal para acompanhar o chá ou o cafezinho da tarde. Um verdadeiro luxo!",
        'categorias' => [2, 4],
    ],
    [
        'nome' => 'Torta de nozes',
        'img' => '1539801384604-torta-de-nozes.jpg',
        'destaque' => true,
        'preco' => 20,
        'descricao' => "Esta é a sobremesa certa para grandes comemorações. É chique e muito gostosa, um clássico da família da Rita. Chama torta mas na verdade é bolo, com massa de nozes, recheio de baba de moça e cobertura de merengue. Imagine! Ou melhor, experimente.",
        'categorias' => [2],
    ],
    [
        'nome' => 'Brigadeiro com coco queimado',
        'img' => '1500925815054-briga3.jpg',
        'destaque' => true,
        'preco' => .6,
        'descricao' => "O clássico das festinhas de aniversário em uma versão levemente mais complexa: o chocolate amargo combinado aos flocos de coco queimado reforça o time dos sabores de tosta, criando um equilíbrio todo diferente à doçura do leite condensado.",
        'categorias' => [5],
    ],

    // Brigadeiros
    [
        'nome' => 'Brigadeiro com nibs de cacau',
        'img' => '1500923984819-briga2.jpg',
        'destaque' => true,
        'preco' => .7,
        'descricao' => "Versão do clássico das festinhas feita sob medida para os fãs de cacau. Além de levar chocolate amargo na massa, esse brigadeiro é coberto com nibs crocantes de cacau.",
        'categorias' => [5],
    ],
    [
        'nome' => 'Brigadeiro especial',
        'img' => '1500921091680-briga1.jpg',
        'destaque' => true,
        'preco' => .5,
        'descricao' => "Essa receita de brigadeiro é diferente. O chocolate amargo equilibra a doçura do leite condensado – e se você usar a dica do batedor de arame, no final da receita, vai ter um docinho mais cremoso. Para finalizar, invista em um granulado de boa qualidade, isso faz toda a diferença.",
        'categorias' => [5],
    ],
    [
        'nome' => 'Brigadeiro tradicional',
        'img' => '958014000000-Brigadeiro.jpg',
        'destaque' => false,
        'preco' => .4,
        'descricao' => "O brigadeiro é um doce genuinamente brasileiro. Um orgulho só! Essa delícia de chocolate faz a alegria da criançada e de muita gente grande em qualquer circunstância. Veja aqui a receita original e delicie-se.",
        'categorias' => [5],
    ],
    [
        'nome' => 'brigadeiros com morango',
        'img' => 'brigadeiro_3.jpg',
        'destaque' => true,
        'preco' => 1.3,
        'descricao' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam rhoncus tellus nisi. Suspendisse eget lacus tellus. Quisque gravida dictum lorem in tincidunt. Vivamus nibh quam, maximus eget fermentum et, imperdiet sed velit.",
        'categorias' => [4, 5],
    ],

    // bolos
    [
        'nome' => 'Bolo de cenoura com merengue e pistache',
        'img' => '1553279647734-bolocenoura.jpg',
        'destaque' => true,
        'preco' => 18,
        'descricao' => 'Sua busca por um bolo de aniversário de adulto acabou. O bolo cenoura ganhou versão festiva, com perfume de raspas de laranja e canela e uma camada de merengue salpicado de pistaches.',
        'categorias' => [1],
    ],
    [
        'nome' => 'Bolo de chocolate com amendoim',
        'img' => '1523394206196-1520971956731-bolo receita_.jpg',
        'destaque' => true,
        'preco' => 23.5,
        'descricao' => 'O segredo para deixar o bolo úmido sem precisar de calda está escondido bem aqui, nesta receita. E a combinação de chocolate com amendoim, hein? Um arraso.',
        'categorias' => [1, 4],
    ],
    [
        'nome' => 'Bolo de ricota com maçã',
        'img' => '1519928060303-bolo-maca.jpg',
        'destaque' => true,
        'preco' => 24.5,
        'descricao' => 'Quem olha, vê um bolo simples, de furo no meio. Quem corta a massa, nota que é úmido e perfumado. E quem prova descobre que trata-se de uma receita surpreendente, elegante, única! Compõe a mesa do chá da tarde, transforma o café da manhã em festa e faz bonito até como sobremesa – ainda mais com gomos de laranja macerados!',
        'categorias' => [1],
    ],
    [
        'nome' => 'Bolo suspiro com maracujá',
        'img' => '1513026667377-bolo-receita.jpg',
        'destaque' => true,
        'preco' => 25,
        'descricao' => 'É naked cake, é bolo que já sai do forno com a cobertura pronta, é receita do tipo "uauuuu" para impressionar os convidados. Doce demais? Não! O maracujá empresta seu azedinho e deixa tudo deliciosamente equilibrado.',
        'categorias' => [1],
    ],
    [
        'nome' => 'Bolo mármore de cenoura com chocolate',
        'img' => '1575563596961-1513026030385-bolo-mesclado-receitavale.jpg',
        'destaque' => true,
        'preco' => 21,
        'descricao' => 'E se a gente juntar dois clássicos, o bolo marmorizado com o de cenoura? Já é! Para melhorar ainda mais o que já tem tudo para ficar bom, uma cobertura durinha por fora e macia por dentro.',
        'categorias' => [1, 4],
    ],
    [
        'nome' => 'Bolo de iogurte com especiarias',
        'img' => '1540923366850-receita-esta.jpg',
        'destaque' => false,
        'preco' => 18,
        'descricao' => 'A base é de um bolo simples. O iogurte é o segredo para deixar a massa super macia. Feito no liquidificador e perfumado com cravo, canela, gengibre, cardamomo e noz-moscada, fica com sabor inspirado no chai, bebida de leite com especiarias e chá preto.',
        'categorias' => [1],
    ],
    [
        'nome' => 'Bolo de mel e maçã',
        'img' => '1410922800000-Bolo-de-mel-e-maca.jpg',
        'destaque' => true,
        'preco' => 19,
        'descricao' => 'Mel e maçã são símbolos do Rosh Hashaná, o Ano Novo Judaico. Mas não precisa ter data marcada pra fazer este bolo, que é perfumado, levemente doce e ainda tem cobertura de maçãs carameladas!',
        'categorias' => [1],
    ],
    [
        'nome' => 'Bolo de fubá com compota de goiaba',
        'img' => '1557151824019-CP-2019-08-02_7132.jpg',
        'destaque' => true,
        'preco' => 19,
        'descricao' => 'No lugar dos quadradinhos de goiabada na massa, a goiaba virou compota e foi para o alto do bolo. Fica enfeitado, mas vai além: a calda, que tem sabor da fruta e um toque canela, é absorvida pela massa, que fica ainda mais perfumada e saborosa. ',
        'categorias' => [1],
    ],

    [
        'nome' => "Brigadeiro de Halloween",
        'img' => "brigadeiro_halloween.jpg",
        'destaque' => true,
        'preco' => .99,
        'descricao' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam rhoncus tellus nisi. Suspendisse eget lacus tellus. Quisque gravida dictum lorem in tincidunt. Vivamus nibh quam, maximus eget fermentum et, imperdiet sed velit.",
        'categorias' => [4, 5, 6],
    ],
    [
        'nome' => 'Formas de chocolate',
        'img' => 'formas_chocolate_halloween_1.jpg',
        'destaque' => false,
        'preco' => .99,
        'descricao' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam rhoncus tellus nisi. Suspendisse eget lacus tellus. Quisque gravida dictum lorem in tincidunt. Vivamus nibh quam, maximus eget fermentum et, imperdiet sed velit.",
        'categorias' => [4, 6],
    ],
    [
        'nome' => 'Formas de chocolate',
        'img' => 'formas_chocolate_halloween_2.jpg',
        'destaque' => false,
        'preco' => .78,
        'descricao' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam rhoncus tellus nisi. Suspendisse eget lacus tellus. Quisque gravida dictum lorem in tincidunt. Vivamus nibh quam, maximus eget fermentum et, imperdiet sed velit.",
        'categorias' => [4, 6],
    ],

];
